config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'most_sales/index'
 
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cart_saveds, only: [:destroy, :show, :index, :create, :recover_sale] do
    member do 
      get 'recover_sale'
    end
  end

  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
      get 'cancel'
      get 'new_sale'
      get 'add_with_sanner'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
      post 'import_exel'
    end 
  end 

  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  resources :categories
  resources :companies
  resources :invoice_temps
  resources :invoice_historics do 
    collection do 
      get 'destroy_until'
    end
  end
  resources :profiles
  resources :plans, except: [:new]  
  resources :sectors
  resources :suppliers


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true
  
  has_many :profiles 
  has_one_attached :image
  has_one :plan
  has_one :profile
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_company

  include CompanyConcerns

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.build_address
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        register_date_company_used_the_app(@company)
       
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end
    
    def invalid_company
      logger.error "Invalid company #{params[:id]}"
      redirect_to plans_url, info: "Invalid company."
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(
        :name, 
        :email, 
        :image, 
        :whatsapp, 
        :telephone,
        :nif, 
        address_attributes: [:id, :street, :city_id, :_destroy] 
      )
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div class="container col-lg-10 my-4" id="<%= dom_id company %>" >
  <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
      <div class="card-body">
        <div class="card-title text-center">
                <%= render "image", image: company.image %>
        </div>
        <h4 class="text-center text-pink"><%= company.name %></h4>
        
        <div class="text-center my-2 text-primary-emphasis"> 
          <strong><%= Company.human_attribute_name(:nif) %>:</strong> <%= company.nif %><br>
          <strong>Email:</strong>  <%= company.email %> <br>
          <strong><%= Address.model_name.human(count: 1) %>: </strong> 
            <%= company.address.street %>, 
            <%= company.address.city.city_name %>,  
            <%= company.address.city.province.province_name %>
            <br>

          <strong>
            <%= Company.human_attribute_name(:whatsapp) %>: <%= company.whatsapp %>,
            <%= Company.human_attribute_name(:telephone) %>: <%= company.telephone %>
          </strong>
        </div>

        <div class="mb-3 d-grid gap-2">
            <%= link_to t("links.edit"), edit_company_path(company), class: "btn btn-info" %> 
        </div>
      </div>
   </div>
  </div>

app/views/companies/_form.html.erb
<div class="container col-lg-6 my-4">
  <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
      <div class="card-body">
  
      <%= bootstrap_form_with(model: company) do |form| %>
        <% if company.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

            <ul>
              <% company.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

          <%= form.text_field :name %> 
          <%= form.file_field :image %>
          <%= form.text_field :nif %> 
          <%= form.email_field :email %>
          <%= form.telephone_field :whatsapp, label: Profile.human_attribute_name(:whatsapp), 
              class: 'text-light-emphasis' %>
          <%= form.telephone_field :telephone, label: Profile.human_attribute_name(:telephone), 
          class: 'text-light-emphasis' %>
          
          <%= form.collection_select :province_id, Province.order(:province_name), :id, :province_name, 
          { label: Province.model_name.human(count: 1) }, 
          {class:"province province_select text-light-emphasis"} %> 
            
          <%= form.fields_for :address do |address_form| %>
            <%= address_form.collection_select :city_id, City.order(:city_name), :id, :city_name, 
            { label: City.model_name.human(count: 1)},  {class:"city_select text-light-emphasis"}%>
            <%= address_form.text_field :street, label: Address.human_attribute_name(:street), 
            class: 'text-light-emphasis' %>
          <% end %> 
              
       
          <div class="mb-3 d-grid gap-2">
            <%= form.submit class: "btn btn-info" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/_image.html.erb
<% if !image.attached? %>

    <svg class="bd-placeholder-img rounded-circle" width="140" height="140" 
        role="img" aria-label="Placeholder: 140x140" 
        preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Upload an imagem</title>
        <rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" 
        fill="#777" dy=".3em">140x140</text>
    </svg>
<% else %>

    <%= image_tag(image, width:"140", height:"140", role:"img", class: "rounded-circle" ) %>
    
<% end %>

app/views/companies/edit.html.erb
<h5 class="fs-3 text-center">Editing company</h5>
<%= render "form", company: @company %>

app/views/companies/index.html.erb
<h5 class="fs-3 text-center">Companies</h5>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
  <% end %>
</div>

app/views/companies/new.html.erb
<h5 class="fs-3 text-center">New company</h5>
<%= render "form", company: @company %>

app/views/companies/show.html.erb
<h5 class="fs-3 text-center">company</h5>
<%= render @company %>