config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'most_sales/index'
 
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cart_saveds, only: [:destroy, :show, :index, :create, :recover_sale] do
    member do 
      get 'recover_sale'
    end
  end

  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
      get 'cancel'
      get 'new_sale'
      get 'add_with_sanner'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
      post 'import_exel'
    end 
  end 

  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  resources :categories
  resources :companies
  resources :invoice_temps
  resources :invoice_historics do 
    collection do 
      get 'destroy_until'
    end
  end
  resources :profiles
  resources :plans, except: [:new]  
  resources :sectors
  resources :suppliers


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name_category)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">

  <th scope="row"><%= category.id %></th>
  <td><%= category.name_category %></td>     
  <td>
    <%= button_to "Destroy", category, method: :delete, class:"btn btn-danger btn-sm" %>
  </td>
  <td>
    <%= link_to "Edit", edit_category_path(category), class:"btn btn-success btn-sm" %>
  </td>

</div>

app/views/categories/_form.html.erb
<div class="container col-lg-6 my-4">
  <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
      <div class="card-body">
      <%= bootstrap_form_with(model: category) do |form| %>
        <% if category.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
              <% category.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

          <%= form.text_field :name_category %>

        <div class="mb-3 d-grid gap-2">
          <%= form.submit class: "btn btn-info" %>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h5 class="fs-3 text-center">Editing category</h5>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h5 class="fs-3 text-center">Categories</h5>

<!-- Itens escolhidos-->
<section>
  <div class="col-sm-6" id="sector">
    <table class="table table-hover shadow-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name category</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          
          <% @categories.each do |category| %>
            <%= render category %>
          <% end %>
          
        </tbody>
      </table>
    </div>
</section>
   

app/views/categories/new.html.erb
<h5 class="fs-3 text-center">New category</h5>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h5 class="fs-3 text-center">Category</h5>

<!-- Itens escolhidos-->
<section>
  <div class="col-sm-6" id="sector">
    <table class="table table-hover shadow-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name category</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          
          <%= render @category %>
          
        </tbody>
      </table>
    </div>
</section>