config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get 'most_sales/index'
 
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cart_saveds, only: [:destroy, :show, :index, :create, :recover_sale] do
    member do 
      get 'recover_sale'
    end
  end

  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
      get 'cancel'
      get 'new_sale'
      get 'add_with_sanner'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
      post 'import_exel'
    end 
  end 

  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  resources :categories
  resources :companies
  resources :invoice_temps
  resources :invoice_historics do 
    collection do 
      get 'destroy_until'
    end
  end
  resources :profiles
  resources :plans, except: [:new]  
  resources :sectors
  resources :suppliers


  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :company

  scope :find_by_company, ->(company) { find_by(company_id: company.id)}
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /plans or /plans.json
  def index
    profile ||= current_user.profile

    if profile.super_adminstrador?
      @plans ||= Plan.all
    else
      @plans ||= Plan.find_by_company(profile.company)
    end
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy!

    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def invalid_cart
      logger.error "Invalid cart #{params[:id]}"
      redirect_to plans_url, info: "Invalid cart."
    end
    
    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:sign_date, :expiration_date, :company_id)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
 <div class="container col-lg-6 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <%= bootstrap_form_with(model: plan) do |form| %>
            <% if plan.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

                <ul>
                  <% plan.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%= form.date_field :sign_date %>
            <%= form.date_field :expiration_date %>

            <%= form.collection_select :company_id, Company.order(:name), :id, :name, 
            { label: Company.model_name.human(count: 1) }, 
            {class:"text-light-emphasis"} %> 


            <div class="mb-3 d-grid gap-2">
              <%= form.submit class: "btn btn-info" %>
            </div>
          <% end %>
        </div>
    </div>
 </div>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
    <th scope="row"><%= plan.id %></th>
    <td scope="col"><%= plan.sign_date %></td>
    <td scope="col"><%= plan.expiration_date %></td>
    <td scope="col"><%= plan.company.name %></td>
    <% if current_user.profile.super_adminstrador? %>
      <td>
        <%= button_to "Destroy", plan, method: :delete, class:"btn btn-danger btn-sm",
        form:{ data: { turbo_confirm: "Tens a certeza que pretendes eliminar este item?"} } %>
      </td>
      <td>
        <%= link_to "Edit", edit_plan_path(plan), class:"btn btn-success btn-sm" %>
      </td>
    <% end %>
</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Show this plan", @plan %> |
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/index.html.erb
    
    <!-- Plans index-->
    <h5 class="fs-3 text-center">Plans</h5>

    <section>
      <table class="table table-hover shadow-sm">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Data Assinatura</th>
              <th scope="col">Data Expiração</th>
              <th scope="col">Empresa</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
              <div id="plans">
                  <% @plans.each do |plan| %>
                    <tr>
                      <%= render plan %>
                    </tr>
                  <% end %>
              </div>
          </tbody>
        </table>
        <% if @plans.empty? %>
          <p class="fs-2 text-success text-center">
            No Plans found.
          </p>
        <% end %>
    </section>

    <!-- Fim Plans index-->

app/views/plans/show.html.erb
    
    <!-- Plans index-->
    <h5 class="fs-3 text-center">Plans</h5>

    <section>

    <div>
      <%= link_to "Back to plans", plans_path %>
    </div>
      <table class="table table-hover shadow-sm">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Data Assinatura</th>
              <th scope="col">Data Expiração</th>
              <th scope="col">Empresa</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
              <div id="plans">
                <tr>
                  <%= render @plan %>
                </tr>
              </div>
          </tbody>
        </table>
    </section>

    <!-- Fim Plans index-->